import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class ProductService {
    getProductsData() {
        return [
            {

                weight: '1 گرم',
                price: 6650000,
                fee: '15000',
                activeIndex: 0,
                isInWishList: false,
                id: '1012',
                code: '250vm23cc',
                name: 'انگشتر طلا',
                description: 'Product Description',
                image: 'green-t-shirt.jpg',
                category: 'طلای زینتی',
                quantity: 74,
                inventoryStatus: 'INSTOCK',
                rating: 5,
                images: [
                    { id: '13.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {

                weight: '1 گرم',
                price: 1560000,
                fee: '17000',
                activeIndex: 0,
                isInWishList: false,
                id: '1013',
                code: 'f230fh0g3',
                name: 'گردنبند طلا',
                description: 'Product Description',
                image: 'bamboo-watch.jpg',
                category: 'طلای زینتی',
                quantity: 24,
                inventoryStatus: 'INSTOCK',
                rating: 5,
                images: [
                    { id: '14.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 1960000,
                fee: '14000',
                activeIndex: 0,
                isInWishList: false,
                id: '1014',
                code: 'nvklal433',
                name: 'دستبند طلا',
                description: 'Product Description',
                image: '2.webp',
                category: 'طلای زینتی',
                quantity: 61,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 4,
                images: [
                    { id: '15.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 450000,
                fee: '11000',
                activeIndex: 0,
                isInWishList: false,
                id: '1015',
                code: 'zz21cz3c1',
                name: 'گوشواره طلا',
                description: 'Product Description',
                image: '3.webp',
                category: 'طلای زینتی',
                quantity: 2,
                inventoryStatus: 'LOWSTOCK',
                rating: 3,
                images: [
                    { id: '4.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {

                weight: '1 گرم',
                price: 50000,
                fee: '19000',
                activeIndex: 0,
                isInWishList: false,
                id: '1008',
                code: 'vbb124btr',
                name: 'پلاک 2.5 گرمی',
                description: 'Product Description',
                image: 'game-controller.jpg',
                category: 'طلای آب شده',
                quantity: 2,
                inventoryStatus: 'LOWSTOCK',
                rating: 4,
                images: [
                    { id: '9.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {

                weight: '1 گرم',
                price: 880000,
                fee: '20000',
                activeIndex: 0,
                isInWishList: false,
                id: '1009',
                code: 'cm230f032',
                name: 'پلاک 5 گرمی',
                description: 'Product Description',
                image: 'gaming-set.jpg',
                category: 'طلای آب شده',
                quantity: 63,
                inventoryStatus: 'INSTOCK',
                rating: 3,
                images: [
                    { id: '10.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {

                weight: '1 گرم',
                price: 940000,
                fee: '16000',
                activeIndex: 0,
                isInWishList: false,
                id: '1010',
                code: 'plb34234v',
                name: 'پلاک 10 گرمی',
                description: 'Product Description',
                image: 'gold-phone-case.jpg',
                category: 'طلای آب شده',
                quantity: 0,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 4,
                images: [
                    { id: '11.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {

                weight: '1 گرم',
                price: 1250000,
                fee: '25000',
                activeIndex: 0,
                isInWishList: false,
                id: '1011',
                code: '4920nnc2d',
                name: 'شمش نقره 500 گرمی',
                description: 'Product Description',
                image: 'green-earbuds.jpg',
                category: 'شمش نقره',
                quantity: 23,
                inventoryStatus: 'INSTOCK',
                rating: 4,
                images: [
                    { id: '12.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 120000,
                fee: '12000',
                activeIndex: 0,
                isInWishList: false,
                id: '1000',
                code: 'f230fh0g3',
                name: 'گردنبند طلا',
                description: 'Product Description',
                image: 'bamboo-watch.jpg',
                category: 'طلای زینتی',
                quantity: 24,
                inventoryStatus: 'INSTOCK',
                rating: 5,
                images: [
                    { id: '1.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 180000,
                fee: '19000',
                activeIndex: 0,
                isInWishList: false,
                id: '1001',
                code: 'nvklal433',
                name: 'دستبند طلا',
                description: 'Product Description',
                image: '2.webp',
                category: 'طلای زینتی',
                quantity: 61,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 4,
                images: [
                    { id: '2.webp' },
                    { id: '1.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 750000,
                fee: '17000',
                activeIndex: 0,
                isInWishList: false,
                id: '1002',
                code: 'zz21cz3c1',
                name: 'گوشواره طلا',
                description: 'Product Description',
                image: '3.webp',
                category: 'طلای زینتی',
                quantity: 2,
                inventoryStatus: 'LOWSTOCK',
                rating: 3,
                images: [
                    { id: '3.webp' },
                    { id: '2.webp' },
                    { id: '1.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 950000,
                fee: '22000',
                activeIndex: 0,
                isInWishList: false,
                id: '1003',
                code: '244wgerg2',
                name: 'انگشتر طلا',
                description: 'Product Description',
                image: '4.webp',
                category: 'طلای زینتی',
                quantity: 25,
                inventoryStatus: 'INSTOCK',
                rating: 5,
                images: [
                    { id: '20.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '1.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 350000,
                fee: '28000',
                activeIndex: 0,
                isInWishList: false,
                id: '1004',
                code: 'h456wer53',
                name: 'پابند طلا',
                description: 'Product Description',
                image: 'bracelet.jpg',
                category: 'طلای زینتی',
                quantity: 73,
                inventoryStatus: 'INSTOCK',
                rating: 4,
                images: [
                    { id: '5.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 190000,
                fee: '31000',
                activeIndex: 0,
                isInWishList: false,
                id: '1005',
                code: 'av2231fwg',
                name: 'سرویس کامل طلا',
                description: 'Product Description',
                image: 'brown-purse.jpg',
                category: 'طلای زینتی',
                quantity: 0,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 4,
                images: [
                    { id: '6.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {

                weight: '1 گرم',
                price: 3350000,
                fee: '33000',
                activeIndex: 0,
                isInWishList: false,
                id: '1006',
                code: 'bib36pfvm',
                name: 'حلقه ازدواج',
                description: 'Product Description',
                image: 'chakra-bracelet.jpg',
                category: 'طلای زینتی',
                quantity: 5,
                inventoryStatus: 'LOWSTOCK',
                rating: 3,
                images: [
                    { id: '7.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {

                weight: '1 گرم',
                price: 850000,
                fee: '24000',
                activeIndex: 0,
                isInWishList: false,
                id: '1007',
                code: 'mbvjkgip5',
                name: 'زنجیر طلا',
                description: 'Product Description',
                image: 'galaxy-earrings.jpg',
                category: 'طلای زینتی',
                quantity: 23,
                inventoryStatus: 'INSTOCK',
                rating: 5,
                images: [
                    { id: '8.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 7250000,
                fee: '42000',
                activeIndex: 0,
                isInWishList: false,
                id: '1016',
                code: '244wgerg2',
                name: 'انگشتر طلا',
                description: 'Product Description',
                image: '4.webp',
                category: 'طلای زینتی',
                quantity: 25,
                inventoryStatus: 'INSTOCK',
                rating: 5,
                images: [
                    { id: '17.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 8150000,
                fee: '39000',
                activeIndex: 0,
                isInWishList: false,
                id: '1017',
                code: 'h456wer53',
                name: 'پابند طلا',
                description: 'Product Description',
                image: 'bracelet.jpg',
                category: 'طلای زینتی',
                quantity: 73,
                inventoryStatus: 'INSTOCK',
                rating: 4,
                images: [
                    { id: '18.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
            {
                weight: '1 گرم',
                price: 846000,
                fee: '41000',
                activeIndex: 0,
                isInWishList: false,
                id: '1018',
                code: 'av2231fwg',
                name: 'سرویس کامل طلا',
                description: 'Product Description',
                image: 'brown-purse.jpg',
                category: 'طلای زینتی',
                quantity: 0,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 4,
                images: [
                    { id: '19.webp' },
                    { id: '2.webp' },
                    { id: '3.webp' },
                    { id: '4.webp' },
                ]
            },
        ];
    }


    getProductsMini() {
        return Promise.resolve(this.getProductsData().slice(0, 5));
    }

    getProducts() {
        return Promise.resolve(this.getProductsData());
    }
};